import type { VisaCountry } from "@/lib/visas/types"

/**
 * Legacy Visa Lounge destinations — deduplicated canonical list.
 * legacyUrl values are preserved from the WordPress site where verified.
 */
export const visaCountries: VisaCountry[] = [
  { slug: "australia", name: "Australia", isoCode: "AU", legacyUrl: "/australia" },
  { slug: "austria", name: "Austria", isoCode: "AT" },
  { slug: "azerbaijan", name: "Azerbaijan", isoCode: "AZ" },
  { slug: "cambodia", name: "Cambodia", isoCode: "KH" },
  { slug: "canada", name: "Canada", isoCode: "CA", legacyUrl: "/canada" },
  {
    slug: "china",
    name: "China",
    isoCode: "CN",
    legacyUrl: "/china-business-summary",
  },
  { slug: "croatia", name: "Croatia", isoCode: "HR" },
  { slug: "czech-republic", name: "Czech Republic", isoCode: "CZ" },
  { slug: "denmark", name: "Denmark", isoCode: "DK" },
  { slug: "egypt", name: "Egypt", isoCode: "EG", legacyUrl: "/egypt" },
  { slug: "finland", name: "Finland", isoCode: "FI", legacyUrl: "/fineland" },
  { slug: "france", name: "France", isoCode: "FR", legacyUrl: "/france" },
  { slug: "georgia", name: "Georgia", isoCode: "GE" },
  { slug: "greece", name: "Greece", isoCode: "GR", legacyUrl: "/greece" },
  { slug: "hong-kong", name: "Hong Kong", isoCode: "HK" },
  { slug: "iceland", name: "Iceland", isoCode: "IS" },
  {
    slug: "indonesia",
    name: "Indonesia",
    isoCode: "ID",
    legacyUrl: "/indonesia",
  },
  { slug: "italy", name: "Italy", isoCode: "IT", legacyUrl: "/italy" },
  {
    slug: "japan",
    name: "Japan",
    isoCode: "JP",
    legacyUrl: "/japan-tourist-summary",
  },
  { slug: "jordan", name: "Jordan", isoCode: "JO" },
  { slug: "kenya", name: "Kenya", isoCode: "KE" },
  { slug: "laos", name: "Laos", isoCode: "LA" },
  { slug: "lithuania", name: "Lithuania", isoCode: "LT", legacyUrl: "/lithunia" },
  { slug: "luxembourg", name: "Luxembourg", isoCode: "LU" },
  { slug: "malta", name: "Malta", isoCode: "MT" },
  { slug: "morocco", name: "Morocco", isoCode: "MA" },
  {
    slug: "netherlands",
    name: "Netherlands",
    isoCode: "NL",
    legacyUrl: "/netherland",
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    isoCode: "NZ",
    legacyUrl: "/new-zealand",
  },
  { slug: "oman", name: "Oman", isoCode: "OM", legacyUrl: "/oman" },
  {
    slug: "portugal",
    name: "Portugal",
    isoCode: "PT",
    legacyUrl: "/portugal-toursit",
  },
  { slug: "russia", name: "Russia", isoCode: "RU" },
  { slug: "singapore", name: "Singapore", isoCode: "SG", legacyUrl: "/singapore" },
  {
    slug: "south-africa",
    name: "South Africa",
    isoCode: "ZA",
    legacyUrl: "/south-africa",
  },
  {
    slug: "south-korea",
    name: "South Korea",
    isoCode: "KR",
    legacyUrl: "/south-korea",
  },
  {
    slug: "spain",
    name: "Spain",
    isoCode: "ES",
    legacyUrl: "/spain-tourist-summary/",
  },
  { slug: "sweden", name: "Sweden", isoCode: "SE" },
  {
    slug: "switzerland",
    name: "Switzerland",
    isoCode: "CH",
    legacyUrl: "/switzerland",
  },
  { slug: "taiwan", name: "Taiwan", isoCode: "TW" },
  { slug: "thailand", name: "Thailand", isoCode: "TH", legacyUrl: "/thailand" },
  { slug: "turkey", name: "Turkey", isoCode: "TR", legacyUrl: "/turkey" },
  {
    slug: "united-arab-emirates",
    name: "United Arab Emirates",
    isoCode: "AE",
    legacyUrl: "/__dubai-tourist-visa-summay",
  },
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    isoCode: "GB",
    legacyUrl: "/united-kingdom",
  },
  { slug: "united-states", name: "United States", isoCode: "US" },
  { slug: "uzbekistan", name: "Uzbekistan", isoCode: "UZ" },
  { slug: "vietnam", name: "Vietnam", isoCode: "VN", legacyUrl: "/vietnam" },
]
